server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: keycloak-interceptor
          uri: https://github.com/cavanosa/microservices-tutorial
          search-paths: config-data
  application:
    name: config-service
